name: GlobalChem API

on: [pull_request, push, workflow_dispatch]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.7", "3.8", "3.9"]
        include:
          - python-version: "3.7"
            coverage-version: "4.5.3"
          - python-version: "3.8"
            coverage-version: "4.5.4"
          - python-version: "3.9"
            coverage-version: "5.0"

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install
        run: |
          python global_chem/setup.py install
          pip install python-coveralls
          pip install coveralls
          pip install coverage==${{ matrix.coverage-version }}
          pip install nose

      - name: Run GlobalChem tests
        env:
          GITHUB_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          cd global_chem
          python -m nose --verbose --with-coverage -s -w tests/
